import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['src/tests/**/*.test.ts'],
    exclude: [
      'src/tests/appState*.test.ts',
      'src/tests/fileWatcher.test.ts',
      'src/tests/ipcUtils*.test.ts',
      'src/tests/preload.test.ts',
      'src/tests/undoRedoManager.ipc.test.ts',
      'src/tests/updateManager*.test.ts',
      'src/tests/windowManager*.test.ts',
      'src/tests/settingsManager*.test.ts',
      'src/tests/homeSettingsManager.test.ts',
      'src/tests/archiveManager*.test.ts',
      'src/tests/archiveSafety.test.ts',
      'src/tests/backupManager*.test.ts',
      'src/tests/diagnosticsHandlers*.test.ts',
      'src/tests/diskSpaceHandler.test.ts',
      'src/tests/elevatedOperations*.test.ts',
      'src/tests/fileOperations*.test.ts',
      'src/tests/fileTasks.test.ts',
      'src/tests/fullDiskAccess.test.ts',
      'src/tests/gitHandlers*.test.ts',
      'src/tests/indexer*.test.ts',
      'src/tests/platformUtils*.test.ts',
      'src/tests/searchHandlers*.test.ts',
      'src/tests/systemHandlers*.test.ts',
      'src/tests/zoomHandlers.test.ts',
      'src/tests/security*.test.ts',
      'src/tests/hiddenFileCache*.test.ts',
      'src/tests/thumbnailCache*.test.ts',
      'src/tests/undoRedoManager*.test.ts',
      'src/tests/processUtils.test.ts',
      'src/tests/fileAnalysis.test.ts',
      'src/tests/openWithHandlers.test.ts',
      'src/tests/fileOperationUtils.test.ts',
      'src/tests/utils/logger*.test.ts',
      'src/tests/workers/**',
      'src/tests/build.dependency-preflight.test.ts',
      'src/tests/build.smoke-scripts.test.ts',
      'src/tests/build.test-all.test.ts',
      'src/tests/build.post-release-assets.test.ts',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      include: ['src/**/*.ts'],
      exclude: ['src/tests/**/*.test.ts', 'src/main/**', 'src/workers/**', 'src/renderer.ts'],
    },
  },
});
