import type { Settings } from './types';

export function createDefaultSettings(): Settings {
  return {
    transparency: true,
    theme: 'default',
    useSystemTheme: false,
    sortBy: 'name',
    sortOrder: 'asc',
    bookmarks: [],
    viewMode: 'grid',
    showDangerousOptions: false,
    startupPath: '',
    showHiddenFiles: false,
    enableSearchHistory: true,
    searchHistory: [],
    directoryHistory: [],
    enableIndexer: true,
    minimizeToTray: false,
    startOnLogin: false,
    autoCheckUpdates: true,
    launchCount: 0,
    supportPopupDismissed: false,
    tourPromptDismissed: false,
    tourCompleted: false,
    skipFullDiskAccessPrompt: false,
    recentFiles: [],
    folderIcons: {},
    showRecentFiles: true,
    showFolderTree: true,
    enableTabs: true,
    globalContentSearch: false,
    enableSyntaxHighlighting: true,
    enableGitStatus: false,
    showFileHoverCard: true,
    showFileCheckboxes: false,

    reduceMotion: false,
    highContrast: false,
    largeText: false,
    boldText: false,
    visibleFocus: false,
    reduceTransparency: false,
    uiDensity: 'default',
    updateChannel: 'auto',
    themedIcons: false,
  };
}
